services:
  # Backend Service
  - type: web
    name: freelancer-backend
    env: docker
    dockerContext: backend of the project
    dockerfilePath: backend of the project/Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: DB_URL
        fromGroup: db-settings
      - key: DB_USERNAME
        fromGroup: db-settings
      - key: DB_PASSWORD
        fromGroup: db-settings

envVarGroups:
  - name: db-settings
    envVars:
      - key: DB_URL
        value: jdbc:mysql://mysql-190fe3fd-rbnarule2002-3e09.g.aivencloud.com:24165/defaultdb?sslMode=REQUIRED
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_VmWI7YYokW7B0q19Pzt
